In [1]:
import numpy as np

In [6]:
s = (1,2,3,4,5)
print(s)

(1, 2, 3, 4, 5)


In [5]:
H = np.array(s)
print(H)

[1 2 3 4 5]


In [8]:
a = np.arange(10)
s = slice(2,6,2) # slice(start, condition, increment)
print(a[s])

[2 4]


In [10]:
a = np.array([[1,2,3], [3,4,5], [4,5,6]])
print("Our array is: ")
print(a)

Our array is: 
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [15]:
print("The items in the 2nd row are: ")
print(a[1, ...])

The items in the 2nd row are: 
4


In [14]:
print("The items in column 1 onwards: ")
print(a[...,1])

The items in column 1 onwards: 
[2 4 5]
